### ISSUE TITLE
Error with CSS using this Theme

### ISSUE THREAD

**Issue by stive101** [DNA-styx/HLSTATSX-Windmill-Theme#1]
Hello, 

i got solved a bit of issues, the purple.css theme has to be copied also into /assets/css (wich is not in the repo)

but several "css?"  issue are left, the admin page looks not formattet and when u click on awards, its also not working

Next Problem : 

Multiple Servers for 1 Game is also wont working, the second server from the same game looks not good and all is black

error log Awards :

for awards : 
hlstats.php?mode=awards&game=struder:373 Uncaught ReferenceError: Tabs is not defined
    at hlstats.php?mode=awards&game=struder:373:2
(anonymous) @ hlstats.php?mode=awards&game=struder:373

**Comment by DNA-styx** [comment]
HI!

Thanks for testing out this theme, it's not quite ready for public release as most public pages are themed but not the admin ones.

I'll look to get multiple servers formatted on the main page next.

- css
Thanks. I've fixed that. the css does need to stay in the styles folder so the purple bar can be changed to a different colour from the admin interface.

- Admin pages
Best turn on the light theme when doing admin stuff. I'll start theming these pages once I have all the public pages finished.

- Awards page
Thanks that's really helpful.  I cans see the problem. Work arround go to admin settings and change 'Use tabs in playerinfo to show/hide sections current page or just show all at once' to 'old style'. I'll work on a fix

**Comment by DNA-styx** [comment]
Awards page issue fixed. Grab the current awards.php file

**Comment by stive101** [comment]
Thanks, also an idea with multiple server on the same game ? Issue

**Comment by DNA-styx** [comment]
> Will you implement the Server statistics too , server uptime , playerslots ...

Will add it as a feature request. I removed them to simplify the pages and the default graphs don't really fit in with the theme. Let me see what I can do.

 > I got google maps working on hlstats , think the maps window in your editet pages wont will show up actually without changing some stuff right ?

Yes, again I removed google maps to simplify the pages. To be honest I also didn't really see the point of it. Why do you use it?

> I also using a ts3 voice server fix that u can add voice server to hlstats frontpage, any chance that u can integrate that too ?

Feature request added

Thanks @stive101

**Comment by stive101** [comment]
Hello,

For the statistics, perhaps you could add it like in the preview demo from Windmill Dashboard/Charts: [Windmill Dashboard](https://windmill-dashboard.vercel.app/?form=MG0AV3&form=MG0AV3) under "General Statistics" and in the Server Overview Page below the server. I think that would fit well.

Regarding the feature request for multiple servers, making them foldable or collapsible would help to get a better overview, especially when including more features for each server to have a clearer view. 

Google Maps is not that important, that's right, but I spent hours figuring out how to make it work, and I did find a solution. That's why I want that feature included; it is a standard feature of HLstatsX, and I just want all given features working.

If you don't want Google Maps because of the simple overview, I understand that, but in this case, you should remove the function completely from the settings and the page code as well, so that new users don't activate it and search for the feature, only to wonder why it isn’t working.

I'm still happy to follow progress in this, you did great work on it, thanks for that.
