### ISSUE TITLE
Player 50/50

### ISSUE THREAD

**Issue by Trice1984** [DNA-styx/HLSTATSX-Windmill-Theme#12]
Hello am again

when server full, 50/50 it doesnt show alle Player see:

![50player](https://github.com/user-attachments/assets/ad7fa8b2-2aec-4e47-ac8a-8c1e7c4e5fa0)

It only a idea that thats work :-)

LG Trice

**Comment by DNA-styx** [comment]
Thanks for reporting and testing my theme. I've not see it running against any high pop servers yet. I've spotted a couple of things needing fixed.

Back to the issue you reported...did you see this same issue with the default theme?

~~I did a search for any high pop servers running HLStatsx but the highest I could find was ~24. Wondering if it's a hard limit in HLStatx.~~ Just found a 27 player HLDM server but it's running HLStatsx v1.7.0

One possibly connected thing I noticed was your Links drop down menu didn't include this server either.

Let me do a bit of digging.

**Comment by Trice1984** [comment]
Good Morning DNA-styx, thank u for Check that Player(Limit).
YEs The links are complete confuse :/.  :-(

have a good Day

**Comment by DNA-styx** [comment]
I see that the cssNOpro page is now displaying the correct player numbers. 

I'll keep an watch out for it happening elsewhere again.

**Comment by Trice1984** [comment]
Yes its now correct, now we Check The ts3 Server things, when Click on The Name some error comes, we have the Click disabled and now we Test. Serveradmin Password is correct but errors come.Gesendet mit der mobilen Mail AppAm 10.11.24 um 22:00 schrieb DNA-styx
                
            
            
                
                    Von: "DNA-styx" ***@***.***>Datum: 10. November 2024An: "DNA-styx/HLSTATSX-Windmill-Theme" ***@***.***>Cc: "Trice001" ***@***.***>,"Author" ***@***.***>Betreff: Re: [DNA-styx/HLSTATSX-Windmill-Theme] Player 50/50 (Issue #12)
                
                
I see that the cssNOpro page is now displaying the correct player numbers.
I'll keep an watch out for it happening elsewhere again.

**Comment by DNA-styx** [comment]
> but errors come.

Sorry about that, it's a bug in my code. [Just fixed it ](https://github.com/DNA-styx/HLSTATSX-Windmill-Theme/commit/a5dc36e1a9b833c6fb96925c26df7a25542afba5)

**Comment by Trice1984** [comment]
I have updatet all files, now a question to TS3, Is there a way to display the channel lists? When click on " Servername" there is nothing :-/

[https://stats.xloldies.de/hlstats.php](url)

**Comment by DNA-styx** [comment]
Have posted some WIP screenshots over here #18
