### ISSUE TITLE
TeamSpeak3 - Add channel listing page

### ISSUE THREAD

**Issue by DNA-styx** [DNA-styx/HLSTATSX-Windmill-Theme#18]

**Comment by DNA-styx** [comment]
Work in progress:
![image](https://github.com/user-attachments/assets/90c84a73-b432-4c8d-8f58-f586249797c8)
![image](https://github.com/user-attachments/assets/12e223d5-a7e4-47cc-b320-6b51dfbaf752)

**Comment by DNA-styx** [comment]
What sort of stuff is useful to pull from the server? There's a fine light between providing useful info and oversharing server settings...I'm currently pulling welcome message, banners, platform/version 

<details>
<summary>but there's lots more</summary>

`
  *  [virtualserver_unique_identifier] => 1GvKR12fg/mY75flwN/u7pn7KIs=
  *  [virtualserver_name] => TeamSpeak ]I[ Server
  *  [virtualserver_welcomemessage] => Welcome to TeamSpeak, check [URL]www.teamspeak.com[/URL] for latest information
  *  [virtualserver_platform] => Windows
  *  [virtualserver_version] => 3.0.12.4 [Build: 1461597405]
  *  [virtualserver_maxclients] => 32
  *  [virtualserver_password] => 
  *  [virtualserver_clientsonline] => 2
  *  [virtualserver_channelsonline] => 1
  *  [virtualserver_created] => 0
  *  [virtualserver_uptime] => 6517
  *  [virtualserver_codec_encryption_mode] => 0
  *  [virtualserver_hostmessage] => 
  *  [virtualserver_hostmessage_mode] => 0
  *  [virtualserver_filebase] => files\\virtualserver_1
  *  [virtualserver_default_server_group] => 11
  *  [virtualserver_default_channel_group] => 12
  *  [virtualserver_flag_password] => 0
  *  [virtualserver_default_channel_admin_group] => 9
  *  [virtualserver_max_download_total_bandwidth] => 18446744073709551615
  *  [virtualserver_max_upload_total_bandwidth] => 18446744073709551615
  *  [virtualserver_hostbanner_url] => 
  *  [virtualserver_hostbanner_gfx_url] => 
  *  [virtualserver_hostbanner_gfx_interval] => 0
  *  [virtualserver_complain_autoban_count] => 5
  *  [virtualserver_complain_autoban_time] => 1200
  *  [virtualserver_complain_remove_time] => 3600
  *  [virtualserver_min_clients_in_channel_before_forced_silence] => 100
  *  [virtualserver_priority_speaker_dimm_modificator] => -18.0000
  *  [virtualserver_id] => 1
  *  [virtualserver_antiflood_points_tick_reduce] => 5
  *  [virtualserver_antiflood_points_needed_command_block] => 150
  *  [virtualserver_antiflood_points_needed_ip_block] => 250
  *  [virtualserver_client_connections] => 1
  *  [virtualserver_query_client_connections] => 54
  *  [virtualserver_hostbutton_tooltip] => 
  *  [virtualserver_hostbutton_url] => 
  *  [virtualserver_hostbutton_gfx_url] => 
  *  [virtualserver_queryclientsonline] => 1
  *  [virtualserver_download_quota] => 18446744073709551615
  *  [virtualserver_upload_quota] => 18446744073709551615
  *  [virtualserver_month_bytes_downloaded] => 0
  *  [virtualserver_month_bytes_uploaded] => 16045
  *  [virtualserver_total_bytes_downloaded] => 0
  *  [virtualserver_total_bytes_uploaded] => 16045
  *  [virtualserver_port] => 9987
  *  [virtualserver_autostart] => 1
  *  [virtualserver_machine_id] => 
  *  [virtualserver_needed_identity_security_level] => 8
  *  [virtualserver_log_client] => 0
  *  [virtualserver_log_query] => 0
  *  [virtualserver_log_channel] => 0
  *  [virtualserver_log_permissions] => 1
  *  [virtualserver_log_server] => 0
  *  [virtualserver_log_filetransfer] => 0
  *  [virtualserver_min_client_version] => 1445512488
  *  [virtualserver_name_phonetic] => 
  *  [virtualserver_icon_id] => 0
  *  [virtualserver_reserved_slots] => 0
  *  [virtualserver_total_packetloss_speech] => 0.0000
  *  [virtualserver_total_packetloss_keepalive] => 0.0000
  *  [virtualserver_total_packetloss_control] => 0.0000
  *  [virtualserver_total_packetloss_total] => 0.0000
  *  [virtualserver_total_ping] => 0.0000
  *  [virtualserver_ip] => 
  *  [virtualserver_weblist_enabled] => 1
  *  [virtualserver_ask_for_privilegekey] => 0
  *  [virtualserver_hostbanner_mode] => 0
  *  [virtualserver_channel_temp_delete_delay_default] => 0
  *  [virtualserver_min_android_version] => 1407159763
  *  [virtualserver_min_ios_version] => 1407159763
  *  [virtualserver_status] => online
  *  [connection_filetransfer_bandwidth_sent] => 0
  *  [connection_filetransfer_bandwidth_received] => 0
  *  [connection_filetransfer_bytes_sent_total] => 0
  *  [connection_filetransfer_bytes_received_total] => 0
  *  [connection_packets_sent_speech] => 0
  *  [connection_bytes_sent_speech] => 0
  *  [connection_packets_received_speech] => 0
  *  [connection_bytes_received_speech] => 0
  *  [connection_packets_sent_keepalive] => 12959
  *  [connection_bytes_sent_keepalive] => 531319
  *  [connection_packets_received_keepalive] => 12959
  *  [connection_bytes_received_keepalive] => 544277
  *  [connection_packets_sent_control] => 396
  *  [connection_bytes_sent_control] => 65555
  *  [connection_packets_received_control] => 397
  *  [connection_bytes_received_control] => 44930
  *  [connection_packets_sent_total] => 13355
  *  [connection_bytes_sent_total] => 596874
  *  [connection_packets_received_total] => 13356
  *  [connection_bytes_received_total] => 589207
  *  [connection_bandwidth_sent_last_second_total] => 81
  *  [connection_bandwidth_sent_last_minute_total] => 92
  *  [connection_bandwidth_received_last_second_total] => 83
  *  [connection_bandwidth_received_last_minute_total] => 88
  `
</details>

![image](https://github.com/user-attachments/assets/dd2036ae-3355-4b46-ad7e-621952016de6)

**Comment by Trice1984** [comment]
Hello, its work perfekt, but in Channel, not show the Names.

![ts_no names](https://github.com/user-attachments/assets/9879da4f-9a33-44c4-97dc-0ff8d696b5c2)

**Comment by DNA-styx** [comment]
@Trice1984 

Thanks for reporting. 

What are these (in red)? Are they a way to group Channels? How do you create them?

They seem to have HTML in them that is breaking the tree view which is stopping it from expanding.

![image](https://github.com/user-attachments/assets/c02c2e0f-f329-4b14-9896-4a42dd5a6e6c)

**Comment by DNA-styx** [comment]
@Trice1984 Fix for #24  is here if you want to edit the file yourself, otherwise it will be fixed in the next release:

https://github.com/DNA-styx/HLSTATSX-Windmill-Theme/commit/79c0d66e14ed36eb633918d1cab495eeb9da1135
