### ISSUE TITLE
PHP error / New TS3 Server Overview Screen

### ISSUE THREAD

**Issue by stive101** [DNA-styx/HLSTATSX-Windmill-Theme#23]
Im Updatet to the newest version and got this error after klick on my ts3 Server : 

```
[20-Nov-2024 21:30:54 UTC] PHP Fatal error:  Uncaught TypeError: fputs(): supplied resource is not a valid stream resource in /home//www/includes/teamspeak3/ts3ssv.php:192
Stack trace:
#0 /home//www/includes/teamspeak3/ts3ssv.php(192): fputs()
#1 /home//www/includes/teamspeak3/ts3ssv.php(468): ts3ssv->disconnect()
#2 /home//www/pages/teamspeak.php(33): ts3ssv->render()
#3 /home//www/hlstats.php(228): include('...')
#4 {main}
  thrown in /home//www/includes/teamspeak3/ts3ssv.php on line 192
```

**Comment by DNA-styx** [comment]
Thanks for reporting.

I normally only ever see that message if the TS3 server being queried is offline and I refresh the server details page. (if the server is offline the link to the server details page is not built on the front page, so you shouldn't be able to get to it). Seems there is a bug in the TS3 class file I'm using just on the details page that detects an offline server as online, then throws the above error when it tries to close the connection. Can't see a fix for it and no other forks have one either, but I'll keep an eye out for it.

I've added some code to the v0.1.28dev release that closes all TS3 connections just in case that was causing it.

**Comment by stive101** [comment]
No, the fatal error is gone,.
