### ISSUE TITLE
Feature request / Visual addition.TS3 Voice Server - Channel Overview 

### ISSUE THREAD

**Issue by stive101** [DNA-styx/HLSTATSX-Windmill-Theme#26]
Feature request / Visual addition.

Please open the channel user overview by default when a user is in this channel. This way, when you open the TS3 server overview, you can see the users in the channel without having to open the channel overview manualy .

**Comment by Trice1984** [comment]
Yes, even when TS View, u must "open" a marked channel

![TSopen](https://github.com/user-attachments/assets/89a15307-0de4-4d54-abc9-b669a3cf0949)


Thank u for the fast support every moment thats great!

**Comment by DNA-styx** [comment]
Very easy fix to expand all channels - I didn't enable it by default as I was concerned folks with very busy channels would end up with a veryyyyyyyyy long web page :) - but I can add it to the settings file for the next prerelease.

Open includes/teamspeak3/ts3ssv.php line 404

Change from:

`<sl-tree-item>$image&nbsp;<span class="text-gray-600 dark:text-gray-400">$name</span>&nbsp;$flags`
to
`<sl-tree-item expanded>$image&nbsp;<span class="text-gray-600 dark:text-gray-400">$name</span>&nbsp;$flags`

There is also a couple of settings to hide empty channels. If that's something useful I can move it to the settings file as well.

web/pages/teamspeak.php line 28 & 29

> $ts3ssv->hideEmptyChannels = false;
> $ts3ssv->hideParentChannels = false;

@Trice1984 there is a broken image beside your name in the picture you posted. Can you right click on where the image should be and select 'open image in new tab', then post what the image is?

**Comment by stive101** [comment]
@DNA-styx 

Could you modify it so that only the channels with online players are auto-expanded? I don't think we need all of the channels expanded by default.

**Comment by Trice1984** [comment]
Hello the image Name :
hlstatsimg/teamspeak3/purple/group_2505261566.png  i have edit the Name of the right PIC to -group_2505261566.png ,  so it now show the PIC

**Comment by DNA-styx** [comment]
> @DNA-styx 
> 
> Could you modify it so that only the channels with online players are auto-expanded? I don't think we need all of the channels expanded by default.

That's a bit tricky, let me have a look..

How about hiding the empty channels? That way only ones with players will be expanded?

**Comment by DNA-styx** [comment]
> Hello the image Name :
> hlstatsimg/teamspeak3/purple/group_2505261566.png  i have edit the Name of the right PIC to -group_2505261566.png ,  so it now show the PIC

Interesting. You must be a member of a custom server admin group and they have their own group pics named using the group id.

**Comment by stive101** [comment]
> > @DNA-styx
> > Could you modify it so that only the channels with online players are auto-expanded? I don't think we need all of the channels expanded by default.
> 
> That's a bit tricky, let me have a look..
> 
> How about hiding the empty channels? That way only ones with players will be expanded?

sure, thats an option, but then when u are a new player, u have no option to see, if the ts has a channel for your game u wanna talk about as example. 

The old TS3 fix, displays all channels expanded i think. im only using 6 or 7 channels thats why im not think about the big list issue :=)

maybe u find a different solution, when not, i think with hide empty channels i can work :=)

**Comment by Trice1984** [comment]
> Very easy fix to expand all channels - I didn't enable it by default as I was concerned folks with very busy channels would end up with a veryyyyyyyyy long web page :) - but I can add it to the settings file for the next prerelease.
> 
> Open includes/teamspeak3/ts3ssv.php line 404
> 
> Change from:
> 
> `<sl-tree-item>$image&nbsp;<span class="text-gray-600 dark:text-gray-400">$name</span>&nbsp;$flags` to `<sl-tree-item expanded>$image&nbsp;<span class="text-gray-600 dark:text-gray-400">$name</span>&nbsp;$flags`
> 
> There is also a couple of settings to hide empty channels. If that's something useful I can move it to the settings file as well.
> 
> web/pages/teamspeak.php line 28 & 29
> 
> > $ts3ssv->hideEmptyChannels = false;
> > $ts3ssv->hideParentChannels = false;
> 
> @Trice1984 there is a broken image beside your name in the picture you posted. Can you right click on where the image should be and select 'open image in new tab', then post what the image is?

NOW its work perfect by us!
