### ISSUE TITLE
routing issue on ts3 channels overview

### ISSUE THREAD

**Issue by stive101** [DNA-styx/HLSTATSX-Windmill-Theme#28]
My installation is not located at /www, but rather at /www/hlstats.

I have resolved most issues with the following Nginx configuration:

```
server {
    listen 80;  
    server_name stats.uri.org;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;  
    server_name stats.uri.org;

    # SSL Certificates
    ssl_certificate /etc/letsencrypt/live/stats.uri.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/stats.uri.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location = / {
        return 301 /hlstats/;
    }

    # `/hlstats` location
    location /hlstats {
        proxy_pass http://proxiip:port;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```
This configuration works for most of the standard HLStats pages. However, for the TeamSpeak 3 channel overview, the browser is trying to access the overview page at the wrong document root:

https://uri/hlstats.php?mode=teamspeak&tsId=1

And it returns a "not found" error, because it should be:

https://uri/hlstats/hlstats.php?mode=teamspeak&tsId=1

I haven't figured out why this happens. Maybe you have an idea? It seems to be an issue only with the channel overview.
Maybe to clarify, on the total overview page where your gameservers and voiceservers locatet, its the (view) button wich are pointent to the wrong adress ( / but should be /hlstats

**Comment by DNA-styx** [comment]
Thanks for reporting.

Would you be able to test if editing pages -> voicecomm_serverlist.php line 123 fixes it?

Change 
`&nbsp;<a href="<?php echo $g_options['scripturl'] . "?mode=teamspeak&amp;game=$game&amp;tsId=".$ts_server['serverId']; ?>"><?php echo trim($ts_server['name']); ?></a>`
to
`&nbsp;<a href="<?php echo "?mode=teamspeak&amp;game=$game&amp;tsId=".$ts_server['serverId']; ?>"><?php echo trim($ts_server['name']); ?></a>`

**Comment by stive101** [comment]
its line 113/114 an no didnt fix the issue, 

i guess problem is in the overview where gameserver and voice server is locatet when u see the (view) button. that button has the wrong link,

**Comment by stive101** [comment]
for the fix, its line 113/114

no that didnt helped,

think must be somthing to do with

line 215

```
$ts3q_server_page = $ts3q_server_name . "&nbsp;<a href=\"/hlstats.php?mode=teamspeak&tsId=" . $ts3_id . "\">(View)</a>";
```

**Comment by stive101** [comment]
yes that fixed it :=)
