### ISSUE TITLE
missing mutet picture for ts3 icon package ? 

### ISSUE THREAD

**Issue by stive101** [DNA-styx/HLSTATSX-Windmill-Theme#29]
those image are missing : 

img src="./hlstatsimg/teamspeak3/purple/input_muted.png
<img width="470" alt="Screenshot 2024-11-23 174359" src="https://github.com/user-attachments/assets/5965a8dd-c538-43b1-b31d-0e13865d86db">

Theme v0.1.32dev

**Comment by DNA-styx** [comment]
Thanks for reporting. That's it added to the repo download from here: https://github.com/DNA-styx/HLSTATSX-Windmill-Theme/commit/9ba933ccea34e4899ea0b71b799032034e1eb47c
