### ISSUE TITLE
Admin - CSS files not appearing in drop down

### ISSUE THREAD

**Issue by DNA-styx** [DNA-styx/HLSTATSX-Windmill-Theme#37]
https://forums.alliedmods.net/showpost.php?p=2831372&postcount=3

![image](https://github.com/user-attachments/assets/8fd714c5-e78c-4e7a-a227-5632f672c882)
![image](https://github.com/user-attachments/assets/d703fa71-b247-44e9-8c3a-744b4184bbd0)

Working on my test site

![image](https://github.com/user-attachments/assets/3dbed874-ea2f-43fd-86d1-1397ca788eec)

**Comment by crywolfy** [comment]
I have uploaded them again and overwrited same thing, Theme is now shown in Display style selector.

**Comment by DNA-styx** [comment]
Thank you for your extensive testing.

After you have uploaded the file, the entire site will change automatically, the CSS chooser is just if you want to change from the default purple.

Can you give me a link to the site you are testing the theme on? Is it the one link on the website in your GitHub profile? Message it to me privately if you wish.

**Comment by crywolfy** [comment]
Thanks for answering as well, i did send you a PM with details on Allied Modders

**Comment by DNA-styx** [comment]
Not a problem @crywolfy , glad you got sorted :)

Thanks for trying the theme, it's very useful, I've noticed a couple of bugs in the theme that doesn't appear on my test site.
