### ISSUE TITLE
Feature Request  Join/View Button in a different color

### ISSUE THREAD

**Issue by stive101** [DNA-styx/HLStatsX-Windmill-Theme#39]
Feature Request 
Make the Join/View Button in a different color to make it easyer to find.

**Comment by DNA-styx** [comment]
Perhaps make it purple? (or whatever custom colour the admin selects?)

![image](https://github.com/user-attachments/assets/228edb29-137e-4c0f-a6e4-6e52bf4b9dc4)

**Comment by stive101** [comment]
sounds good :=)

**Comment by stive101** [comment]
and also pls dont forget to colorisize also the game server (Join) button :=)
thanks :P

**Comment by DNA-styx** [comment]
![image](https://github.com/user-attachments/assets/ed2320ee-8427-4a25-9303-0800bea1d596)
 :)
