### ISSUE TITLE
Steam Group chat just link to steam group overview

### ISSUE THREAD

**Issue by stive101** [DNA-styx/HLStatsX-Windmill-Theme#40]
Hello,

should the Steam Group add funktion give u the ability to join the group or to join the groups chat ? 

the way u descripe in the wiki only adds a overview of your steamgroup, when that should be the function, i think you should rename the name " Steam Group Chat (Join)  to Join Steam Group (Join) or somthing like that

edit : or visit Steam Group (Join)

**Comment by DNA-styx** [comment]
Good point, think it should be called 'Steam Group'. Will correct.

**Comment by DNA-styx** [comment]
Like that?

![image](https://github.com/user-attachments/assets/3975251f-d49a-458a-90db-527e11055012)

**Comment by DNA-styx** [comment]
Or I could add both links to the group and the chat. If people would use both.

**Comment by stive101** [comment]
that is better yes, 

but for the chat, im not sure how usefull that is, becouse u need to login to steam first, 
i think i find all in the overview of the group,

the actual slots, iks that the online group members or the chat ?

**Comment by DNA-styx** [comment]
This is the data I can access for a group. The slots figure is made up of 

`membersInChat / total memberCount`

```<memberList>
<groupID64>103582791474860457</groupID64>
<groupDetails>
<groupName>
<![CDATA[ HLStatsX-Community-Edition ]]>
</groupName>
<groupURL>
<![CDATA[ HLStatsX-CE ]]>
</groupURL>
<headline>
<![CDATA[ ]]>
</headline>
<summary>
<![CDATA[ Group for testing HLSTATSX-Windmill-Theme's ability to view details of Steam Groups.<br><br><a class="bb_link" href="https://steamcommunity.com/linkfilter/?u=https%3A%2F%2Fgithub.com%2FDNA-styx%2FHLSTATSX-Windmill-Theme" target="_blank" rel=" noopener" >https://github.com/DNA-styx/HLSTATSX-Windmill-Theme</a> ]]>
</summary>
<avatarIcon>
<![CDATA[ https://avatars.cloudflare.steamstatic.com/14322c0756ae3898968426f08bd540ce81987df5.jpg ]]>
</avatarIcon>
<avatarMedium>
<![CDATA[ https://avatars.cloudflare.steamstatic.com/14322c0756ae3898968426f08bd540ce81987df5_medium.jpg ]]>
</avatarMedium>
<avatarFull>
<![CDATA[ https://avatars.cloudflare.steamstatic.com/14322c0756ae3898968426f08bd540ce81987df5_full.jpg ]]>
</avatarFull>
<memberCount>1</memberCount>
<membersInChat>1</membersInChat>
<membersInGame>0</membersInGame>
<membersOnline>1</membersOnline>
</groupDetails>
<memberCount>1</memberCount>
<totalPages>1</totalPages>
<currentPage>1</currentPage>
<startingMember>0</startingMember>
<members>
<steamID64>76561197960305931</steamID64>
</members>
</memberList>

**Comment by stive101** [comment]
hmm im unsure, how activly the chat is used, i think the best option is, to display the overview of the group like before when u klick join ( may that should be named "view" in this case ?)

from the group page on steamcomunitys, when u want u can click join the webchat, otherwise i think, it does not make sense, or u find a way to join the chat without any logins needed. but to show your steam group to others is also a good thing i guess.
