### ISSUE TITLE
Server Page - Feature Request - Maps showing servers & players connected

### ISSUE THREAD

**Issue by DNA-styx** [DNA-styx/HLStatsX-Windmill-Theme#45]
#41

**Comment by DNA-styx** [comment]
Quick tech demo

https://stats.dnagames.site/maps/

This map grabs my server IP's lat/lon and ten random player IP's lat/lon and plots them on a map.

![image](https://github.com/user-attachments/assets/7e287235-6027-4740-8f61-df65d905b743)

**Comment by stive101** [comment]
Hello,

your implamentation of the map overview works a little bit different,

in hlstats, the map marker only shows for aktual players online on the server. thats why the map overview was locatet on the front page were the live players was.

when u klick on the player, u had a tab or a area ( im unsure) where u can see on the map, where his location was on the map.
Im unsure what is better, but i guess, when u display all players registret on the database, its may overfill the map ?

**Comment by DNA-styx** [comment]
Thanks for the background.

The "Ten Random Players" map has no real purpose other than a technology demo :)

The location of live players on the server is on my list.

I've currently only got a very low population server to test this on, so I'm using historical data to start with to see if this mapping system works.

I've added a Top10 players map on the Players Page as the first step: https://stats.dnagames.site/hlstats.php?mode=players&game=dods

**Comment by DNA-styx** [comment]
![image](https://github.com/user-attachments/assets/df56c590-9ab1-4828-8222-b0927db892a1)

Clicking on the point takes you to that player's stats page.

In testing [here](https://stats.dnagames.site/hlstats.php?mode=players&game=dods)

**Comment by DNA-styx** [comment]
That's maps added to the player's page (shows top 50) and the Server's page. I'm quite impressed 

I've removed the lines but left one server always referenced in the map as a way to centre the map.

There are things still needing tidied on it (add a title that respects the night/day theme, make server points different colour, add rank to active player map, embed it in the site rather than an iFrame)....but it's good enough IMHO and I really should finish off theming the admin pages :-)

**Comment by stive101** [comment]
wao, thats very impressiv, 

thats cool, :=) i like it.
Is it possible, to write the Country Name on the countrys at the map, with a transparent color or somtihng like that ? 
Or make a toggle for people who dosnt want names on the map ?
