### ISSUE TITLE
Servers Page - Add TeamSpeak 3

### ISSUE THREAD

**Issue by DNA-styx** [DNA-styx/HLSTATSX-Windmill-Theme#5]
#1

**Comment by stive101** [comment]
hello,

thanks for the ongoing progress, u doing still well, 

One thing to the TS Templates, im not sure about this but i guess u updating the old ones, Those are just for TS1 and 2. 
can u inculde the newest templates that works with team speak 3 ? 

the templates for the hlstats panel was fixed here : 

https://forums.alliedmods.net/showpost.php?p=1854304&postcount=4

**Comment by stive101** [comment]
thank you,

can format the entry page, so that the color theme is active ? 
the voice servers adds a new section on top of Servers section named  Voice Server, 

for now the formating looks like this : 

Voice Servers

testvoiceserver IP blabla

all is black and voiceserver does not have the violett background.

And below there is the Servers section that works well, 
gray color instead of black and section Voice Server with the violett background

**Comment by DNA-styx** [comment]
I've not started applying the theme yet. Just added the original files to the repository.

**Comment by stive101** [comment]
Hey, i checkd the new version. 

i issue i found, (not on your side) is, that following Error

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function ts3_get_data(), 1 passed in /home/container/www/pages/teamspeak.php on line 262 and exactly 2 expected in /home/container/www/pages/teamspeak.php:255
Stack trace:
#0 /home/container/www/pages/teamspeak.php(262): ts3_get_data('virtualserver_n...')
#1 /home/container/www/hlstats.php(228): include('/home/container...')
#2 {main}
  thrown in /home/container/www/pages/teamspeak.php on line 255
  
  ```
  
  i resolved that, that i removed the $data on line 255 but im not sure if that produces any other issues ? maybe u know more about that :=) but that solved the problem and u can get a view into your teamspeak server. 
  
 The Voice Server page is still not themed yet right ? just to inform you, that there is an unthemed Voice Server page if you not know :=)
 
 thanks for adding the voice Servers into the theme.

**Comment by DNA-styx** [comment]
I'm getting a different couple of errors.

With a mumble server added clicking on details gives me this:


```
Fatal error
: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/stats.dnagames.site/pages/ventrilostatus.php:320 Stack trace: #0 /var/www/stats.dnagames.site/pages/ventrilo.php(28): CVentriloStatus->ChannelFind() #1 /var/www/stats.dnagames.site/pages/ventrilo.php(188): VentriloDisplayEX1() #2 /var/www/stats.dnagames.site/hlstats.php(228): include('...') #3 {main} thrown in
/var/www/stats.dnagames.site/pages/ventrilostatus.php
on line
320
```


When I add a TS3 server I get this

```
Stack trace:
    /var/www/stats.dnagames.site/pages/teamspeak3_query.php(133): TSStatus-&gt;queryServer()
    /var/www/stats.dnagames.site/pages/teamspeak3_query.php(276): TSStatus-&gt;update()
    /var/www/stats.dnagames.site/pages/voicecomm_serverlist.php(177): TSStatus-&gt;ts3name()
    /var/www/stats.dnagames.site/pages/game.php(287): include('...')
    /var/www/stats.dnagames.site/pages/contents.php(67): include('...')
    /var/www/stats.dnagames.site/hlstats.php(228): include('...')
    {main}
   thrown in <b>/var/www/stats.dnagames.site/pages/teamspeak3_query.php</b> on line <b>117</b><br />
```

**Comment by stive101** [comment]
Hmm, wow, that's a lot of errors from many pages. I have no idea what that could be. My TS3 server is working with the fixes I mentioned before. I’ve never had those errors and in so many pages. Maybe you modified your HLStats site too much? I have a fresh startersclan just with our theme running and the fixes for the ping/suicide issues.

For TS3, there might be one more thing to consider. For the query port, there are two values in default: 51234/10011. I removed the 51234 and just left the 10011, which helped with adding the server. But that might not be the same error you had. I got no error for the port thing, but the server wasn’t written to the DB.

**Comment by stive101** [comment]
the only error that left for now is following : 

```
2024/10/25 19:52:29 [error] 21#21: *578 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: xxxx , server: , request: "GET /'.IMAGE_PATH.'/teamspeak3/hlstats.php HTTP/1.1", upstream: "fastcgi://unix:/home/container/tmp/php-fpm.sock:", host: "xxx.xxx.xxx", referrer: "http://theipadress.com/hlstats.php?mode=teamspeak&game=nogame&tsId=2"

```

**Comment by stive101** [comment]
i fixed another issue for ts3 

pages/teamspeak3_query.php
line 349/350

fix this : 
"misc3" => time_convert(),
"misc4" => time_convert()  ));

to this : 

"misc3" => time_convert($timestamp),
"misc4" => time_convert($timestamp)  ));

**Comment by DNA-styx** [comment]
> i fixed another issue for ts3
> 
> pages/teamspeak3_query.php line 349/350
> 
> fix this : "misc3" => time_convert(), "misc4" => time_convert() ));
> 
> to this :
> 
> "misc3" => time_convert($timestamp), "misc4" => time_convert($timestamp) ));

Interesting. Can I recommend you create a pull request with that change to [StartClan's HLStatsx](https://github.com/startersclan/hlstatsx-community-edition) (or whichever version you prefer)

**Comment by stive101** [comment]
sry im a total nooby at github :=)

**Comment by DNA-styx** [comment]
> For TS3, there might be one more thing to consider. For the query port, there are two values in default: 51234/10011. I removed the 51234 and just left the 10011, which helped with adding the server. But that might not be the same error you had. I got no error for the port thing, but the server wasn’t written to the DB.

My understanding is that 51234 is for murmur and10011 is for TS/TS3

> edit:
> 
> ok seems like there is a problem with the connection trough the socket, did u add (for ts3) your hlstats server ip into the whiteliste for the teamspeak server ?
> 
> named query_ip_allowlist.txt, only the IP without the ports

Yes, I came across talk of the whitelisting and applied it. 

Also came across talk of makes sure that anonymous guests can connect to TS3 servers, which I can't do using the free TS3 server (https://lemehost.com/)

Also #2 came across that TS3 servers now use a admin query password rather than relying on allowing guest access.

Would you be comfortable sharing details of your TS3 server via my git email? 154759339+DNA-styx@users.noreply.github.com
And also whitelist my web server: 51.195.218.110
This will just be for testing and you can remove the whitelisting whenever you wish.

**Comment by stive101** [comment]
ok im hope i dont forgett anything but u got an email :=)

**Comment by DNA-styx** [comment]
Sorry, I'm confused as to how git email works, you were likely blocked, us this one: dnagames.admin@proton.me

**Comment by stive101** [comment]
ok, im sending email again to the new one

**Comment by DNA-styx** [comment]
Thanks. Getting the same message with your server.

Wondering if it's related to my server's PHP version.

Tthe error says the below making it read like the server address is not being passed to the query script. Did a bit of troubleshooting with echo'ing back what was being requested and it's not passing anything to the query.

`
Uncaught Exception: Socket error: Failed to parse address '' [0] in /var/www/stats.dnagames.site/pages/teamspeak3_query.php:117`

[Tracked down the original code used in the query](https://web.archive.org/web/20150615111030/http://tsstatus.sebastien.me/), but it doesn't work on my php8.1 or 8.3 servers either.

**Comment by stive101** [comment]
Hmm, aktually im using PHP 7.4, maybe the way the socket gots contacted was changed ?

Im not sure but maybe there is something with our forwarding ? because 51.195.218.110 isnt reachable, but that should be the IP address were hlstats run on his webhoste to communikat trough the socket ?

Von: DNA-styx ***@***.***>
Gesendet: Samstag, 26. Oktober 2024 22:33
An: DNA-styx/HLSTATSX-Windmill-Theme ***@***.***>
Cc: stive101 ***@***.***>; Comment ***@***.***>
Betreff: Re: [DNA-styx/HLSTATSX-Windmill-Theme] Servers Page - Add TS and Mumble pages (Issue #5)


Thanks. Getting the same message with your server.

Wondering if it's related to my server's PHP version.

Tthe error says the below making it read like the server address is not being passed to the query script. Did a bit of troubleshooting with echo'ing back what was being requested and it's not passing anything to the query.

Uncaught Exception: Socket error: Failed to parse address '' [0] in /var/www/stats.dnagames.site/pages/teamspeak3_query.php:117

Tracked down the original code used in the query<https://web.archive.org/web/20150615111030/http:/tsstatus.sebastien.me/>, but it doesn't work on my php8.1 or 8.3 servers either.

**Comment by stive101** [comment]
Another test from my side, your website is only reachable trough ssl,
Maybe that blocking the ability for the socket to contact the server because that is not using ssl

The only difference is see is, that when I entered the IP address from my hlstats its working, but when I enter your ip address in the Browser, I cannot get a connection

Von: DNA-styx ***@***.***>
Gesendet: Samstag, 26. Oktober 2024 22:33
An: DNA-styx/HLSTATSX-Windmill-Theme ***@***.***>
Cc: stive101 ***@***.***>; Comment ***@***.***>
Betreff: Re: [DNA-styx/HLSTATSX-Windmill-Theme] Servers Page - Add TS and Mumble pages (Issue #5)


Thanks. Getting the same message with your server.

Wondering if it's related to my server's PHP version.

Tthe error says the below making it read like the server address is not being passed to the query script. Did a bit of troubleshooting with echo'ing back what was being requested and it's not passing anything to the query.

Uncaught Exception: Socket error: Failed to parse address '' [0] in /var/www/stats.dnagames.site/pages/teamspeak3_query.php:117

Tracked down the original code used in the query<https://web.archive.org/web/20150615111030/http:/tsstatus.sebastien.me/>, but it doesn't work on my php8.1 or 8.3 servers either.

**Comment by DNA-styx** [comment]
> Another test from my side, your website is only reachable trough ssl,
> Maybe that blocking the ability for the socket to contact the server because that is not using ssl
Yup, by design, incoming connections to the server are locked down , but outgoing connections are not.

> The only difference is see is, that when I entered the IP address from my hlstats its working, but when I enter your ip address in the Browser, I cannot get a connection
Yes, that's by design. only hostnames work on my server. Direct IP connections will go no where.

I've been able to query my TS server [using this code](https://github.com/Speckmops/ts3admin.class)  
![image](https://github.com/user-attachments/assets/efe7112e-3b65-4a0a-bb97-35cfd8b5ace5)
That rules out my server being locked down.

**Comment by DNA-styx** [comment]
That's some new code added to use TS3 server query to get details from the server.

Add your server query password to [this](https://github.com/DNA-styx/HLSTATSX-Windmill-Theme/blob/8daca90850b2c4c153459d1edc09bb07337bcec8/web/includes/inc_ts3admin_query_password.php) file.

I'll look to expand functionality out to showing who's connected etc.

**Comment by stive101** [comment]
hey, im unsure what ur changed now and why ? for connections, the old script TS3Serverfix wich u got from alienmodders already has that funktion. And im also not know why u working with the Server Query password actually ? is that when the TS3 Server has a passwort set or for what is that then ?

**Comment by stive101** [comment]
im try out the new changes, but now i got that error : 


ERROR
--
Oops, there is a problem (╯°□°）╯︵ ┻━┻If you see this message, please report it to Administrators

**Comment by DNA-styx** [comment]
My reading of the TS3 docs indicates that using the server query password is best practice rather than having to open up guest access.

**Comment by stive101** [comment]
yea sounds logicaly, ok, so that also means, the rights for the Guest are not needet to set anymore ?, thats also good i guess, 

but that also means u have to write your own server orverview now ? so that u can see, who is online and since when, and what are the channels the server has,... ?

**Comment by DNA-styx** [comment]
> yea sounds logicaly, ok, so that also means, the rights for the Guest are not needet to set anymore ?, thats also good i guess,

Yes

> but that also means u have to write your own server orverview now ? so that u can see, who is online and since when, and what are the channels the server has,... ?

yes

>i did a fresh install and now im not getting the oops error again, 

That's an upstream [security fix](https://github.com/A1mDev/hlstatsx-community-edition/commit/cc28820cb449e74e0fb8ab10a46908728e566dbd). Logging back in again fixes it.

> but i see that u should include the ts3 images from the TS3 server fix : hlstatsimg

Thanks for reporting, done so.

**Comment by stive101** [comment]
thanks :=)

**Comment by stive101** [comment]
Hello,

I think I've found a new issue. This existed before you included TS3 in your theme, so it's not on your side.

```
[error] 21#21: *287 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: IP, server: , request: "GET /'.IMAGE_PATH.'/teamspeak3/hlstats.php HTTP/1.0", upstream: "fastcgi://unix:/home/container/tmp/php-fpm.sock:", host: "myurl"
```

While analyzing this with my browser dev tools, I found that the file ts3.css cannot be located. The page that loads when you open your TS3 server overview must have an incorrect link for the ts3.css. I haven't been able to determine which page that is, but maybe you have a better idea where it's located. Some pages where the imgpath is set for ts3.css are working, so there might be a typo or something similar on one of the pages.

**Comment by stive101** [comment]
Hey, 

for the error 

: Uncaught Error: Undefined constant "fopen" in /teamspeak.php

you have to do change

this

```
if(function_exists(fopen))

```

to this 

```
if(function_exists('fopen'))

```

**Comment by stive101** [comment]
hi, 

looks pretty nice, well done :=)
thanks for letting me know u still working on that

**Comment by stive101** [comment]
"I've added a bunch of error reporting code and found this:

```
Unable to write to file: ./includes/teamspeak3/ts3ssv.php.cache

```

I noticed that I missed giving some privileges to the file, and this resolved the error. 😊"
